### ISSUE TITLE
Error when saving ID

### ISSUE THREAD

**Issue by ibigfire** [enra4/discord-schedule-messages#3]
Hiya!  Super sorry, thanks so much for the update you rock!

But for some reason there's now an error when I go to save a contact/ID.

```
>> save IHgeneral <id>
readline.js:1020
            throw err;
            ^

ReferenceError: fileName is not defined
    at rl.question.input (C:\Users\********\Dropbox\Tools\ScheduleMessages\app.js:53:18)
    at Interface._onLine (readline.js:278:5)
    at Interface._line (readline.js:629:8)
    at Interface._ttyWrite (readline.js:910:14)
    at ReadStream.onkeypress (readline.js:158:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1010:36)
```

**Comment by ibigfire** [comment]
Here's an image of the error, if it's at all helpful in any way: https://i.imgur.com/DYXABBX.png

**Comment by enra4** [comment]
sorry about that, was a bit careless. fixed in https://github.com/enra4/discord-schedule-messages/commit/cd0a9fb534dd2902d3409c2b645fdf1f39da795c
